services:
  - type: web
    name: jobconnect
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jobportal.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: jobconnect-db
          property: connectionString

databases:
  - name: jobconnect-db
    databaseName: jobconnect
    user: jobconnect